environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '5'
    - nodejs_version: '4'
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
matrix:
  fast_finish: true
max_jobs: 6
version: '{build}'
shallow_clone: true
clone_depth: 1
build: off
before_test:
  - npm install
test_script:
  - npm test
deploy: off
